### ISSUE TITLE
Collect crash statistic data on each Vision 0 city

### ISSUE THREAD

**Issue by JTurek708** [JTurek708/vision_zero_analysis#2]
Start collecting data related to crash statistics for each city in the Vision 0 Action Network. 

Crash statistics include but not limited to 
- injuries/fatalities of drivers/passengers
- injuries/fatalities of pedestrians 
- injuries/fatalities of bicyclists

**Comment by txmx13** [comment]
https://docs.google.com/spreadsheets/d/1_NtzL4gpi_JaPgO0PwGO87RV7Ex_6HZw7PwTuMMzp9c/edit#gid=0
